//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DM_Console.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEnemy
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Strength { get; set; }
        public string Dexterity { get; set; }
        public string Constitution { get; set; }
        public string Intelligence { get; set; }
        public string Wisdom { get; set; }
        public string Charisma { get; set; }
        public string HitPoints { get; set; }
        public string ArmorClass { get; set; }
        public string Initiative { get; set; }
        public string Speed { get; set; }
        public Nullable<int> STSuccessCount { get; set; }
        public Nullable<int> STFailCount { get; set; }
        public string AdditionalDetails { get; set; }
    }
}
